# Generated by Django 6.0.3 on 2026-10-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('ai', 'AI'), ('backend', 'Backend'), ('web', 'Web')], default='web', max_length=20),
        ),
    ]
